server:
  port: 12080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${FOOTIE_DB_HOST:localhost}:5432/footie
    username: footer
    password: changeme

#springdoc:
#  api-docs:
#    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: info,env,health,beans
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true

testdata:
  loadfile: classpath:epl2019-2020.json
  season: 2019-2020